// frontend-angular/src/app/features/calendar/event-modal.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import {
  AbstractControl,
  FormBuilder,
  ReactiveFormsModule,
  ValidationErrors,
  Validators,
} from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatIconModule } from '@angular/material/icon';
import { UserMultiSelectComponent } from '../../shared/components/user-multi-select.component';
import { EventsStore } from './events.store';
import type { CalendarEvent, EventVisibility } from '../../core/api/api.types';

export const COLOR_PRESETS = [
  '#3B82F6', '#10B981', '#F59E0B', '#EF4444',
  '#8B5CF6', '#EC4899', '#6366F1', '#14B8A6',
] as const;

export interface EventModalData {
  event?: CalendarEvent | null;
  initialStart?: string;
  initialEnd?: string;
}

function endAfterStart(group: AbstractControl): ValidationErrors | null {
  const start = group.get('startTime')?.value as string;
  const end = group.get('endTime')?.value as string;
  if (!start || !end) return null;
  return new Date(end) > new Date(start) ? null : { endBeforeStart: true };
}

// Converts FullCalendar date string to datetime-local value (YYYY-MM-DDTHH:mm)
function toDateTimeLocal(dateStr: string): string {
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    return `${dateStr}T00:00`;
  }
  const d = new Date(dateStr);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

@Component({
  selector: 'app-event-modal',
  imports: [
    ReactiveFormsModule,
    MatButtonModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatIconModule,
    UserMultiSelectComponent,
  ],
  templateUrl: './event-modal.component.html',
  styles: [`
    .visibility-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }
    .vis-btn {
      display: flex; align-items: center; justify-content: center; gap: 6px;
      padding: 10px 8px; border-radius: 8px; border: 2px solid var(--mat-sys-outline);
      background: none; cursor: pointer; font-weight: 500; transition: border-color 0.15s, background 0.15s;
    }
    .vis-btn.selected {
      border-color: var(--mat-sys-primary);
      background: color-mix(in srgb, var(--mat-sys-primary) 10%, transparent);
      color: var(--mat-sys-primary);
    }
    .color-grid { display: flex; gap: 8px; flex-wrap: wrap; }
    .color-swatch {
      width: 36px; height: 36px; border-radius: 50%; border: 3px solid transparent;
      cursor: pointer; transition: box-shadow 0.15s;
    }
    .color-swatch.selected { box-shadow: 0 0 0 3px white, 0 0 0 5px var(--mat-sys-primary); }
    .form-section { display: flex; flex-direction: column; gap: 12px; }
    .date-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .error-text { color: var(--mat-sys-error); font-size: 12px; margin-top: 4px; }
    mat-form-field { width: 100%; }
  `],
})
export class EventModalComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly store = inject(EventsStore);
  readonly dialogRef = inject(MatDialogRef<EventModalComponent>);
  readonly data: EventModalData = inject(MAT_DIALOG_DATA);

  readonly colorPresets = COLOR_PRESETS;
  readonly visibilityOptions: { value: EventVisibility; label: string; icon: string }[] = [
    { value: 'Private', label: 'Private', icon: 'lock' },
    { value: 'Public', label: 'Public', icon: 'public' },
    { value: 'Restricted', label: 'Restricted', icon: 'group' },
  ];

  readonly isSaving = signal(false);
  readonly isDeleting = signal(false);
  readonly isEditing = !!this.data.event;

  readonly form = this.fb.nonNullable.group({
    title: ['', [Validators.required, Validators.maxLength(200)]],
    description: ['', Validators.maxLength(1000)],
    startTime: ['', Validators.required],
    endTime: ['', Validators.required],
    location: ['', Validators.maxLength(200)],
    visibility: ['Public' as EventVisibility, Validators.required],
    color: [COLOR_PRESETS[0] as string],
    allowedUserIds: [[] as string[]],
  }, { validators: endAfterStart });

  ngOnInit(): void {
    const { event, initialStart, initialEnd } = this.data;
    if (event) {
      this.form.setValue({
        title: event.title,
        description: event.description ?? '',
        startTime: toDateTimeLocal(event.startTime),
        endTime: toDateTimeLocal(event.endTime),
        location: event.location ?? '',
        visibility: event.visibility,
        color: event.color ?? COLOR_PRESETS[0],
        allowedUserIds: event.allowedUserIds ?? [],
      });
    } else if (initialStart && initialEnd) {
      this.form.patchValue({
        startTime: toDateTimeLocal(initialStart),
        endTime: toDateTimeLocal(initialEnd),
      });
    }
  }

  get visibility() { return this.form.controls.visibility.value; }
  get allowedUserIds() { return this.form.controls.allowedUserIds.value; }

  setVisibility(v: EventVisibility): void { this.form.controls.visibility.setValue(v); }
  setColor(c: string): void { this.form.controls.color.setValue(c); }
  setAllowedUsers(ids: string[]): void { this.form.controls.allowedUserIds.setValue(ids); }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.isSaving.set(true);
    try {
      const raw = this.form.getRawValue();
      const payload = {
        ...raw,
        startTime: new Date(raw.startTime).toISOString(),
        endTime: new Date(raw.endTime).toISOString(),
        allowedUserIds: raw.visibility === 'Restricted' ? raw.allowedUserIds : [],
      };
      let result: CalendarEvent | null;
      if (this.isEditing && this.data.event) {
        result = await this.store.updateEvent(this.data.event.id, payload);
      } else {
        result = await this.store.createEvent(payload);
      }
      if (result) this.dialogRef.close(true);
    } finally {
      this.isSaving.set(false);
    }
  }

  async onDelete(): Promise<void> {
    if (!this.data.event) return;
    if (!confirm('Delete this event?')) return;
    this.isDeleting.set(true);
    try {
      const ok = await this.store.deleteEvent(this.data.event.id);
      if (ok) this.dialogRef.close(true);
    } finally {
      this.isDeleting.set(false);
    }
  }
}

<h2 mat-dialog-title>{{ isEditing ? 'Edit Event' : 'Create Event' }}</h2>

<mat-dialog-content>
  <form [formGroup]="form" class="form-section" autocomplete="off">

    <mat-form-field appearance="outline">
      <mat-label>Title</mat-label>
      <input matInput formControlName="title" placeholder="Event title" />
      @if (form.controls.title.touched && form.controls.title.hasError('required')) {
        <mat-error>Title is required</mat-error>
      }
      @if (form.controls.title.touched && form.controls.title.hasError('maxlength')) {
        <mat-error>Title must be 200 characters or fewer</mat-error>
      }
    </mat-form-field>

    <mat-form-field appearance="outline">
      <mat-label>Description</mat-label>
      <textarea matInput formControlName="description" rows="3" placeholder="Event description (optional)"></textarea>
      @if (form.controls.description.touched && form.controls.description.hasError('maxlength')) {
        <mat-error>Description must be 1000 characters or fewer</mat-error>
      }
    </mat-form-field>

    <div class="date-row">
      <mat-form-field appearance="outline">
        <mat-label>Start Date &amp; Time</mat-label>
        <input matInput type="datetime-local" formControlName="startTime" />
        @if (form.controls.startTime.touched && form.controls.startTime.hasError('required')) {
          <mat-error>Start time is required</mat-error>
        }
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>End Date &amp; Time</mat-label>
        <input matInput type="datetime-local" formControlName="endTime" />
        @if (form.controls.endTime.touched && form.controls.endTime.hasError('required')) {
          <mat-error>End time is required</mat-error>
        }
        @if (form.controls.endTime.touched && form.hasError('endBeforeStart')) {
          <mat-error>End time must be after start time</mat-error>
        }
      </mat-form-field>
    </div>

    <mat-form-field appearance="outline">
      <mat-label>Location</mat-label>
      <input matInput formControlName="location" placeholder="Event location (optional)" />
      @if (form.controls.location.touched && form.controls.location.hasError('maxlength')) {
        <mat-error>Location must be 200 characters or fewer</mat-error>
      }
    </mat-form-field>

    <!-- Visibility -->
    <div>
      <div class="mat-body-medium" style="margin-bottom: 8px; color: var(--mat-sys-on-surface-variant);">Visibility</div>
      <div class="visibility-grid">
        @for (opt of visibilityOptions; track opt.value) {
          <button type="button" class="vis-btn" [class.selected]="visibility === opt.value" (click)="setVisibility(opt.value)">
            <mat-icon style="font-size: 18px; width: 18px; height: 18px;">{{ opt.icon }}</mat-icon>
            {{ opt.label }}
          </button>
        }
      </div>
    </div>

    <!-- Color presets -->
    <div>
      <div class="mat-body-medium" style="margin-bottom: 8px; color: var(--mat-sys-on-surface-variant);">Color</div>
      <div class="color-grid">
        @for (color of colorPresets; track color) {
          <button
            type="button"
            class="color-swatch"
            [class.selected]="form.controls.color.value === color"
            [style.background-color]="color"
            (click)="setColor(color)"
          ></button>
        }
      </div>
    </div>

    <!-- Allowed users (Restricted only) -->
    @if (visibility === 'Restricted') {
      <app-user-multi-select
        label="Allowed Users"
        [selectedUserIds]="allowedUserIds"
        (selectedUserIdsChange)="setAllowedUsers($event)"
      />
    }

  </form>
</mat-dialog-content>

<mat-dialog-actions align="end">
  @if (isEditing) {
    <button mat-button color="warn" (click)="onDelete()" [disabled]="isDeleting()">
      @if (isDeleting()) {
        <mat-spinner diameter="18" style="display:inline-block"></mat-spinner>
      } @else {
        <mat-icon>delete</mat-icon>
      }
      Delete
    </button>
    <span style="flex: 1"></span>
  }
  <button mat-button mat-dialog-close>Cancel</button>
  <button mat-raised-button color="primary" (click)="onSubmit()" [disabled]="isSaving()">
    @if (isSaving()) {
      <mat-spinner diameter="18" style="display:inline-block;vertical-align:middle;margin-right:4px"></mat-spinner>
    }
    {{ isEditing ? 'Update Event' : 'Create Event' }}
  </button>
</mat-dialog-actions>

// frontend/src/components/calendar/EventModal.tsx
import React, { useEffect } from "react";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { X, Lock, Globe, Users, Save, Trash } from "lucide-react";
import { useCreateEvent, useUpdateEvent } from "../../hooks/useEvents";
import { Button, Input, UserMultiSelect } from "../ui";
import type { Event, EventVisibility } from "../../types";

const eventSchema = z
  .object({
    title: z
      .string()
      .min(1, "Title is required")
      .max(200, "Title must be less than 200 characters"),
    description: z
      .string()
      .max(1000, "Description must be less than 1000 characters")
      .optional(),
    startTime: z.string().min(1, "Start date is required"),
    endTime: z.string().min(1, "End date is required"),
    visibility: z.enum(["Private", "Public", "Restricted"]),
    color: z.string().optional(),
    location: z
      .string()
      .max(200, "Location must be less than 200 characters")
      .optional(),
    allowedUserIds: z.array(z.string()).optional(),
  })
  .refine(
    (data) => {
      // Ensure end date is after start date
      const startDate = new Date(data.startTime);
      const endDate = new Date(data.endTime);
      return endDate > startDate;
    },
    {
      message: "End date must be after start date",
      path: ["endTime"], // Show error on the endTime field
    }
  );

type EventFormData = z.infer<typeof eventSchema>;

interface EventModalProps {
  isOpen: boolean;
  onClose: () => void;
  event?: Event | null;
  initialStart?: string;
  initialEnd?: string;
  onDelete?: (eventId: string) => void;
  isDeleting?: boolean;
}

const visibilityOptions: {
  value: EventVisibility;
  label: string;
  icon: React.ReactNode;
}[] = [
  { value: "Private", label: "Private", icon: <Lock className="w-4 h-4" /> },
  { value: "Public", label: "Public", icon: <Globe className="w-4 h-4" /> },
  {
    value: "Restricted",
    label: "Restricted",
    icon: <Users className="w-4 h-4" />,
  },
];

const colorPresets = [
  "#3B82F6", // blue
  "#10B981", // green
  "#F59E0B", // amber
  "#EF4444", // red
  "#8B5CF6", // purple
  "#EC4899", // pink
  "#6366F1", // indigo
  "#14B8A6", // teal
];

// Format date string for datetime-local input (YYYY-MM-DDTHH:mm)
const formatDateTimeLocal = (dateString: string): string => {
  // Check if it's a date-only string (YYYY-MM-DD) from FullCalendar all-day selection
  // If so, treat it as local midnight, not UTC midnight
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateString)) {
    // Parse manually to avoid UTC interpretation
    const [year, month, day] = dateString.split("-");
    return `${year}-${month}-${day}T00:00`;
  }

  // For datetime strings, parse normally (will use local timezone)
  const date = new Date(dateString);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

export const EventModal: React.FC<EventModalProps> = ({
  isOpen,
  onClose,
  event,
  initialStart,
  initialEnd,
  onDelete,
  isDeleting = false,
}) => {
  const createMutation = useCreateEvent();
  const updateMutation = useUpdateEvent();
  const isEditing = !!event;

  const {
    register,
    handleSubmit,
    control,
    watch,
    reset,
    formState: { errors },
  } = useForm<EventFormData>({
    resolver: zodResolver(eventSchema),
    defaultValues: {
      title: "",
      description: "",
      startTime: initialStart || "",
      endTime: initialEnd || "",
      visibility: "Public",
      color: colorPresets[0],
      location: "",
      allowedUserIds: [],
    },
  });

  const visibility = watch("visibility");

  useEffect(() => {
    if (event) {
      reset({
        title: event.title,
        description: event.description || "",
        startTime: formatDateTimeLocal(event.startTime),
        endTime: formatDateTimeLocal(event.endTime),
        visibility: event.visibility,
        color: event.color || colorPresets[0],
        location: event.location || "",
        allowedUserIds: event.allowedUserIds || [],
      });
    } else if (initialStart && initialEnd) {
      reset({
        title: "",
        description: "",
        startTime: formatDateTimeLocal(initialStart),
        endTime: formatDateTimeLocal(initialEnd),
        visibility: "Public",
        color: colorPresets[0],
        location: "",
        allowedUserIds: [],
      });
    }
  }, [event, initialStart, initialEnd, reset]);

  const onSubmit = (data: EventFormData) => {
    // Convert datetime-local strings (local time) to ISO strings (UTC)
    const startDateTime = new Date(data.startTime);
    const endDateTime = new Date(data.endTime);

    const requestData = {
      ...data,
      startTime: startDateTime.toISOString(),
      endTime: endDateTime.toISOString(),
    };

    if (isEditing) {
      updateMutation.mutate(
        { eventId: event.id, data: requestData },
        {
          onSuccess: () => {
            onClose();
            reset();
          },
        }
      );
    } else {
      createMutation.mutate(requestData, {
        onSuccess: () => {
          onClose();
          reset();
        },
      });
    }
  };

  const handleClose = () => {
    onClose();
    reset();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b">
          <h2 className="text-2xl font-bold text-gray-900">
            {isEditing ? "Edit Event" : "Create Event"}
          </h2>
          <button
            onClick={handleClose}
            className="text-gray-400 hover:text-gray-600 transition"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit(onSubmit)} className="p-6 space-y-6" autoComplete="off">
          <Input
            label="Title"
            placeholder="Event title"
            autoComplete="off"
            error={errors.title?.message}
            {...register("title")}
          />

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Description
            </label>
            <textarea
              {...register("description")}
              rows={3}
              placeholder="Event description (optional)"
              autoComplete="off"
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            {errors.description && (
              <p className="mt-1 text-sm text-red-600">
                {errors.description.message}
              </p>
            )}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <Input
              label="Start Date & Time"
              type="datetime-local"
              autoComplete="off"
              error={errors.startTime?.message}
              {...register("startTime")}
            />
            <Input
              label="End Date & Time"
              type="datetime-local"
              autoComplete="off"
              error={errors.endTime?.message}
              {...register("endTime")}
            />
          </div>

          <Input
            label="Location"
            placeholder="Event location (optional)"
            autoComplete="off"
            error={errors.location?.message}
            {...register("location")}
          />

          {/* Visibility Selector */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Visibility
            </label>
            <Controller
              name="visibility"
              control={control}
              render={({ field }) => (
                <div className="grid grid-cols-3 gap-3">
                  {visibilityOptions.map((option) => (
                    <button
                      key={option.value}
                      type="button"
                      onClick={() => field.onChange(option.value)}
                      className={`flex items-center justify-center space-x-2 px-4 py-3 rounded-lg border-2 transition ${
                        field.value === option.value
                          ? "border-blue-500 bg-blue-50 text-blue-700"
                          : "border-gray-300 hover:border-gray-400"
                      }`}
                    >
                      {option.icon}
                      <span className="font-medium">{option.label}</span>
                    </button>
                  ))}
                </div>
              )}
            />
            {errors.visibility && (
              <p className="mt-1 text-sm text-red-600">
                {errors.visibility.message}
              </p>
            )}
          </div>

          {/* Color Picker */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Color
            </label>
            <Controller
              name="color"
              control={control}
              render={({ field }) => (
                <div className="flex space-x-2">
                  {colorPresets.map((color) => (
                    <button
                      key={color}
                      type="button"
                      onClick={() => field.onChange(color)}
                      className={`w-10 h-10 rounded-full transition ${
                        field.value === color
                          ? "ring-4 ring-offset-2 ring-blue-500"
                          : ""
                      }`}
                      style={{ backgroundColor: color }}
                    />
                  ))}
                </div>
              )}
            />
          </div>

          {/* Restricted Users (shown only when visibility is Restricted) */}
          {visibility === "Restricted" && (
            <Controller
              name="allowedUserIds"
              control={control}
              render={({ field }) => (
                <UserMultiSelect
                  label="Allowed Users"
                  selectedUserIds={field.value || []}
                  onChange={field.onChange}
                />
              )}
            />
          )}

          {/* Actions */}
          <div className="flex justify-between items-center pt-4 border-t">
            {/* Delete button on the left (only shown when editing) */}
            {isEditing && onDelete && event && (
              <Button
                type="button"
                variant="danger"
                onClick={() => onDelete(event.id)}
                isLoading={isDeleting}
              >
                <Trash className="w-4 h-4 mr-2" />
                Delete Event
              </Button>
            )}
            {/* Spacer when no delete button */}
            {(!isEditing || !onDelete) && <div />}

            {/* Cancel and Save buttons on the right */}
            <div className="flex space-x-4">
              <Button type="button" variant="secondary" onClick={handleClose}>
                Cancel
              </Button>
              <Button
                type="submit"
                variant="primary"
                isLoading={createMutation.isPending || updateMutation.isPending}
              >
                <Save className="w-4 h-4 mr-2" />
                {isEditing ? "Update Event" : "Create Event"}
              </Button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
